// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetValue.Data;

#nullable disable

namespace NetValue.Data.Migrations.Sqlite
{
    [DbContext(typeof(SqliteNetValueContext))]
    partial class SqliteNetValueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("NetValue.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ObjectId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NetValue.Data.StorageState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Storage");
                });

            modelBuilder.Entity("NetValue.Data.StoredAccount", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("HouseholdId", "ProfileId", "Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("NetValue.Data.StoredBalance", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Month")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("HouseholdId", "ProfileId", "AccountId", "Month");

                    b.HasIndex("HouseholdId", "ProfileId", "Month");

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("NetValue.Data.StoredHousehold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("NetValue.Data.StoredMember", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("HouseholdId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("NetValue.Data.StoredMonth", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Month")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.HasKey("HouseholdId", "ProfileId", "Month");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("NetValue.Data.StoredProfile", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("HouseholdId", "Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("NetValue.Data.StoredAccount", b =>
                {
                    b.HasOne("NetValue.Data.StoredProfile", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId", "ProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NetValue.Data.StoredBalance", b =>
                {
                    b.HasOne("NetValue.Data.StoredAccount", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId", "ProfileId", "AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NetValue.Data.StoredMonth", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId", "ProfileId", "Month")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NetValue.Data.StoredMember", b =>
                {
                    b.HasOne("NetValue.Data.StoredHousehold", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NetValue.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NetValue.Data.StoredMonth", b =>
                {
                    b.HasOne("NetValue.Data.StoredProfile", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId", "ProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NetValue.Data.StoredProfile", b =>
                {
                    b.HasOne("NetValue.Data.StoredHousehold", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
